
const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';
const FETCHECURRENT = 'FETCHECURRENT';
const USERINFO = 'USERINFO';
const CURRENTUSERID = 'CURRENTUSERID';
const ISSUBMITED = 'ISSUBMITED';
const FETCHEDALLPOST = 'FETCHEDALLPOST';
const SETMOVEORREMOVE = 'SETMOVEORREMOVE';

export { FETCH_NEWS_REQUEST, FETCH_NEWS_SUCCESS, FETCH_NEWS_FAILURE, FETCHECURRENT, USERINFO, CURRENTUSERID, ISSUBMITED, FETCHEDALLPOST, SETMOVEORREMOVE };